### ISSUE TITLE
composer update or installation of other stuff yields 'class not found'

### ISSUE THREAD

**Issue by tachyon-ops** [mamift/redbean4laravel5provider#1]
Hi there!

I am enjoying your module and congrats for it!

I am having some problems:
[RuntimeException]
  Error Output: PHP Fatal error:  Class 'Mamift\Redbean4Laravel5\Redbean4Lar
  avel5Provider' not found in laravel/vendor/laravel/framework/src/Illuminate/Foundati
  on/ProviderRepository.php on line 146

Have you tested this on laravel further?

Thanks

**Comment by mamift** [comment]
Hello, what do you mean by 'other stuff'? Do you mean other composer packages?

You have added 'Mamift\Redbean4Laravel5\Redbean4Laravel5Provider', in the provider array for laravel, right? Or added $app->register('Mamift\Redbean4Laravel5\Redbean4Laravel5Provider'); into app.php for lumen?

**Comment by tachyon-ops** [comment]
Yes, 'Mamift\Redbean4Laravel5\Redbean4Laravel5Provider', in the provider array for laravel 5 (app/config)

Do test it. I suppose you'll get the same error as well. Every time I did installation of other packages, composer didn't recognize the class.

FYI: I have gone manual and I'm using slim - twig and redbean \R: with my costume stuff.

**Comment by mamift** [comment]
Would you mind reproducing your composer.json file here or telling me what other specific composer packages you're including? I cannot reproduce the same error.

**Comment by mamift** [comment]
Of all the things: it was the PSR-4 issue with reconciling the filename to the class name of the Service provider class.
